export const ActionTypes = {
  SET_EMPLOYEES: "SET_EMPLOYEES",
  GET_EMPLOYEES: "GET_EMPLOYEES",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: " DELETE_EMPLOYEE",
  REGISTER_EMPLOYEE: "REGISTER_EMPLOYEE",
};
